import streamlit as st
from parse_tm7 import TM7Parser, dataflows_to_json, threat_model_to_json, generate_tmt_dataframe
from llm_calls import (
    call_API_for_results, 
    generate_dataframe, 
    generate_dataframe_google,
    generate_messages,
    generate_main_content,
    cot,
    fs
)
import tempfile
import os
import json

# from rag import vector_store_from_client

# Page configuration
st.set_page_config(
    page_title="ITA Threat Modeling Tool",
    page_icon="🛡️",
    layout="wide"
)

# Main title
st.title("🛡️ ITA Threat Modeling Tool")
st.markdown("### Threat Analysis with Secure by Design")

st.markdown("---")

# Create two columns for layout
col_left, col_right = st.columns([1, 1])

# LEFT COLUMN - Data Input
with col_left:
    st.header("📝 Data Input")
    
    # .tm7 file upload section
    st.subheader("1. Upload Threat Model File")
    uploaded_file = st.file_uploader(
        "Upload .tm7 file (Microsoft Threat Modeling Tool)",
        type=['tm7'],
        help="File generated by Microsoft Threat Modeling Tool"
    )
    
    # File preview if uploaded
    if uploaded_file is not None:
        st.success(f"✅ File loaded: {uploaded_file.name}")
        with st.expander("📄 File details"):
            st.write(f"**Name:** {uploaded_file.name}")
            st.write(f"**Size:** {uploaded_file.size} bytes")
        
        # Parse file immediately to show diagram selection
        if 'file_parsed' not in st.session_state or st.session_state.get('current_file') != uploaded_file.name:
            try:
                xml_content = uploaded_file.getvalue().decode('utf-8')
                parser = TM7Parser(xml_content)
                threat_model = parser.parse()
                
                st.session_state['threat_model'] = threat_model
                st.session_state['file_parsed'] = True
                st.session_state['current_file'] = uploaded_file.name
                
                num_diagrams = len(threat_model.diagrams)
                if num_diagrams == 0:
                    st.error("❌ No diagrams found in the .tm7 file!")
                elif num_diagrams == 1:
                    st.success(f"✅ File processed successfully! Found {num_diagrams} diagram.")
                    st.session_state['selected_diagram_index'] = 0
                    st.info(f"📊 Diagram automatically selected: {threat_model.diagrams[0].name}")
                else:
                    st.session_state['needs_diagram_selection'] = True
                    
            except Exception as e:
                st.error(f"❌ Error parsing file: {str(e)}")
        
        # Show diagram selection if multiple diagrams
        if st.session_state.get('needs_diagram_selection', False):
            st.markdown("---")
            st.subheader("Select Diagram")
            
            threat_model = st.session_state['threat_model']
            diagram_options = {i: f"{diagram.name} (ID: {i})" 
                              for i, diagram in enumerate(threat_model.diagrams)}
            
            selected_index = st.selectbox(
                "Choose the diagram to analyze:",
                options=list(diagram_options.keys()),
                format_func=lambda x: diagram_options[x],
                help="Select which diagram from the threat model you want to analyze",
                key="diagram_selector"
            )
            
            st.session_state['selected_diagram_index'] = selected_index
    
    st.markdown("---")
    
    # System description section
    st.subheader("2. System Description")
    system_description = st.text_area(
        "Describe the system to be analyzed:",
        height=200,
        placeholder="Describe the architecture, components, data flows, technologies used, etc...",
        help="Provide a detailed description of the system for better threat analysis"
    )
    
    # Information about what was filled
    col1, col2 = st.columns(2)
    with col1:
        if uploaded_file and 'file_parsed' in st.session_state:
            st.metric(".tm7 File", "✅ Loaded")
        else:
            st.metric(".tm7 File", "⏳ Pending")
    
    with col2:
        if system_description:
            st.metric("Description", f"{len(system_description)} characters")
        else:
            st.metric("Description", "⏳ Pending")
    
    st.markdown("---")
    
    # Processing button
    st.subheader("3. Process Data")
    
    analyze_button = st.button(
        "🚀 Process Threat Model",
        type="primary",
        width='stretch',
        disabled=not (uploaded_file and system_description)
    )
    
    # Processing when button is clicked
    if analyze_button:
        with st.spinner("🔄 Processing .tm7 file..."):
            try:
                # Save file temporarily
                with tempfile.NamedTemporaryFile(delete=False, suffix='.tm7', mode='w', encoding='utf-8') as tmp_file:
                    # Read uploaded file content
                    xml_content = uploaded_file.getvalue().decode('utf-8')
                    tmp_file.write(xml_content)
                    tmp_file_path = tmp_file.name
                
                # Parse .tm7 file
                parser = TM7Parser(xml_content)
                threat_model = parser.parse()
                
                # Remove temporary file
                os.unlink(tmp_file_path)
                
                # Save to session_state
                st.session_state['threat_model'] = threat_model
                st.session_state['system_description'] = system_description
                st.session_state['file_processed'] = True
                
                # Check number of diagrams
                num_diagrams = len(threat_model.diagrams)
                
                if num_diagrams == 0:
                    st.error("❌ No diagrams found in the .tm7 file!")
                    st.session_state['analysis_ready'] = False
                else:
                    selected_diagram = threat_model.diagrams[0]
                    if num_diagrams > 1: 
                        selected_diagram = threat_model.diagrams[st.session_state['selected_diagram_index']]
                    
                    json_data = dataflows_to_json(selected_diagram, create_file=False)
                    threat_data = threat_model_to_json(threat_model)
                    st.session_state['json_data'] = json_data
                    st.session_state['threat_data'] = threat_data
                    st.session_state['analysis_ready'] = True
                    st.success(f"✅ File processed successfully! Diagram: {selected_diagram.name}")
                    st.info("📊 Now you can run the AI analysis on the right panel.")
                    
                    # Display threat_data as DataFrame
                    if threat_data:
                        st.markdown("---")
                        st.subheader("🔒 Threats Detected by TMT")
                        
                        try:
                            threat_df = generate_tmt_dataframe(threat_data)
                            
                            with st.expander("📋 Threat Data Table", expanded=True):
                                st.dataframe(threat_df, width='stretch', height=400)
                                
                        except Exception as e:
                            st.warning(f"⚠️ Could not convert threat_data to DataFrame: {str(e)}")
                            with st.expander("📋 Threat Data (JSON)", expanded=True):
                                st.json(threat_data)
                                
            except Exception as e:
                st.error(f"❌ Error processing file: {str(e)}")
                st.exception(e)




                    

# RIGHT COLUMN - Results
with col_right:
    st.header("📊 AI Analysis Results")
    
    if 'analysis_ready' in st.session_state and st.session_state['analysis_ready']:
        st.success("✅ Data loaded and ready for analysis")
        
        # Model selection
        st.subheader("AI Model")
        model_option = st.selectbox(
            "Select model:",
            ["qwen3:8b", "gpt-4.1-nano", "gemini-2.5-flash"],
            help="Choose the AI model for threat analysis",
            key="model_selector"
        )
        
        # Update selected model in session state
        st.session_state['selected_model'] = model_option
        
        # Conditional input fields based on selected model
        if model_option == "gpt-4.1-nano":
            api_key = st.text_input(
                "OpenAI API Key:",
                type="password",
                help="Enter your OpenAI API key",
                key="openai_api_key"
            )
            st.session_state['api_key'] = api_key
            
        elif model_option == "gemini-2.5-flash":
            api_key = st.text_input(
                "Google API Key:",
                type="password",
                help="Enter your Google API key",
                key="google_api_key"
            )
            st.session_state['api_key'] = api_key
            
        elif model_option == "qwen3:8b":
            server_ip = st.text_input(
                "Server IP Address:",
                placeholder="e.g., 192.168.1.100 or localhost",
                help="Enter the IP address of the Ollama server",
                key="ollama_server_ip"
            )
            st.session_state['server_ip'] = server_ip
        
        # Prompt enhancement options
        st.subheader("Prompt Enhancements")
        col_check1, col_check2 = st.columns(2)
        
        with col_check1:
            few_shot_enabled = st.checkbox(
                "Few Shot",
                value=False,
                help="Add few-shot examples to improve model performance"
            )
        
        with col_check2:
            cot_enabled = st.checkbox(
                "Chain of Thoughts",
                value=False,
                help="Enable step-by-step reasoning for better analysis"
            )
        
        st.markdown("---")
        
        # Show basic information
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Model", st.session_state['selected_model'])
        with col2:
            threat_model = st.session_state['threat_model']
            selected_idx = st.session_state.get('selected_diagram_index', 0)
            diagram_name = threat_model.diagrams[selected_idx].name
            st.metric("Diagram", diagram_name[:15] + "..." if len(diagram_name) > 15 else diagram_name)
        with col3:
            st.metric("Description", f"{len(st.session_state['system_description'])} chars")
        
        # Preview of processed data
        with st.expander("🔍 Threat Model Preview (JSON)"):
            st.json(st.session_state.get('json_data', {}))
        
        with st.expander("📝 System Description"):
            st.write(st.session_state.get('system_description', ''))
        
        st.markdown("---")
        
        # AI Analysis Section
        st.subheader("🤖 AI Threat Analysis")
        
        run_analysis_button = st.button(
            "🔍 Run AI Analysis",
            type="primary",
            width='stretch',
            key="run_analysis"
        )
        
        if run_analysis_button:
            with st.spinner(f"🤖 Running analysis with {st.session_state['selected_model']}... This may take a few minutes."):
                try:
                    # Prepare interactions from JSON data
                    json_data = st.session_state.get('json_data', {})
                    system_desc = st.session_state.get('system_description', '')
                    
                    # Generate messages using the interaction
                    messages = generate_messages(json_data)
                    
                    main_content = generate_main_content(system_desc)
                    
                    # Prepare prompt contents based on selected enhancements
                    prompt_contents = [main_content]
                    if few_shot_enabled:
                        prompt_contents.append(fs)
                    if cot_enabled:
                        prompt_contents.append(cot)
                    
                    model_name = st.session_state['selected_model']
                    
                    api_key = st.session_state['api_key'] if 'api_key' in st.session_state else None   
                    server_ip = st.session_state['server_ip'] if 'server_ip' in st.session_state else None
                    
                    # Call appropriate API based on model
                    if model_name == "gpt-4.1-nano":
                        provider = "OPENAI"
                        st.info(f"📡 Calling {model_name} via {provider}...")
                        results = call_API_for_results(messages, prompt_contents, provider, model_name, False, api_key=api_key)
                        df = generate_dataframe(json_data, results, True, f"./data/analysis_{model_name}.csv")
                        
                    elif model_name == "gemini-2.5-flash":
                        provider = "GOOGLE"
                        st.info(f"📡 Calling {model_name} via {provider}...")
                        results = call_API_for_results(messages, prompt_contents, provider, model_name, True, api_key=api_key)
                        df = generate_dataframe_google(json_data, results, True, f"./data/analysis_{model_name}.csv")
                        
                    elif model_name == "qwen3:8b":
                        provider = "OLLAMA"
                        st.info(f"📡 Calling {model_name} via {provider}...")
                        results = call_API_for_results(messages, prompt_contents, provider, model_name, False, server_ip=server_ip)
                        df = generate_dataframe(json_data, results, True, f"./data/analysis_{model_name}.csv")
                    
                    # Save results to session state
                    st.session_state['analysis_results'] = results
                    st.session_state['analysis_df'] = df
                    st.session_state['analysis_complete'] = True
                    
                    st.success(f"✅ Analysis completed with {model_name}!")
                    # st.balloons()
                    
                except Exception as e:
                    st.error(f"❌ Error during analysis: {str(e)}")
                    st.exception(e)
        
        # Display results if analysis is complete
        if st.session_state.get('analysis_complete', False):
            st.markdown("---")
            st.subheader("📋 Analysis Results")
            
            results = st.session_state.get('analysis_results', {})
            
            # Display results in expandable sections
            with st.expander("📊 Full Analysis Report", expanded=False):
                st.write(results)
            
            # Display dataframe if available
            if 'analysis_df' in st.session_state:
                with st.expander("📈 Results Summary (DataFrame)", expanded=True):
                    st.dataframe(st.session_state['analysis_df'], width='stretch')
            
            # Download options
            st.markdown("---")
            st.subheader("💾 Download Results")
            
            col_dl1, col_dl2 = st.columns(2)
            
            with col_dl1:
                # Download JSON
                json_str = st.session_state['analysis_df'].to_json()
                st.download_button(
                    label="📥 Download JSON",
                    data=json_str,
                    file_name=f"threat_analysis_{st.session_state['selected_model']}.json",
                    mime="application/json"
                )
            
            with col_dl2:
                # Download CSV if available
                if 'analysis_df' in st.session_state:
                    csv = st.session_state['analysis_df'].to_csv(index=False)
                    st.download_button(
                        label="📥 Download CSV",
                        data=csv,
                        file_name=f"threat_analysis_{st.session_state['selected_model']}.csv",
                        mime="text/csv"
                    )
            # with col_dl2:
            #     # Download CSV if available
            #     if 'analysis_df' in st.session_state:
            #         csv = st.session_state['analysis_df'].to_csv(index=False)
            #         st.download_button(
            #             label="📥 Download CSV",
            #             data=csv,
            #             file_name=f"threat_analysis_{st.session_state['selected_model']}.csv",
            #             mime="text/csv"
            #         )
            
            # RAG Enhancement Section
            st.markdown("---")
            st.subheader("🔍 RAG Enhancement with NIST")

            k_quant = st.selectbox(
                "Quantity of Controls:",
                [3, 5, 10],
                help="Choose the Quantity of Controls to Include in Analysis (NIST) ",
                key="controls_num_selector"
            )

            st.write("Enhance the analysis with NIST recommendations using RAG (Retrieval Augmented Generation)")
            
            run_rag_button = st.button(
                "🧠 Enhance with RAG",
                type="secondary",
                width='stretch',
                key="run_rag",
                disabled=True
            )
            
            if run_rag_button:
                with st.spinner("🔍 Searching NIST documentation for each threat... This may take a few minutes."):
                    try:
                        df = st.session_state['analysis_df'].copy()
                        rag_results = []
                        
                        # Create progress bar
                        progress_bar = st.progress(0)
                        status_text = st.empty()
                        
                        total_rows = len(df)
                        
                        for idx, row in df.iterrows():
                            # Update progress
                            progress = (idx + 1) / total_rows
                            progress_bar.progress(progress)
                            status_text.text(f"Processing row {idx + 1}/{total_rows}...")
                            
                            # Create question from category and description
                            category = row.get('category', '')
                            description = row.get('description', '')
                            question = f"{category}: {description}"
                            
                            # Perform RAG search
                            try:
                                results = vector_store_from_client.similarity_search(
                                    question,
                                    k=k_quant,
                                )
                                
                                # Join all results
                                rag_text = ", ".join([doc.metadata.get('title') for doc in results])
                                rag_results.append(rag_text)
                                
                            except Exception as e:
                                st.warning(f"⚠️ Error processing row {idx + 1}: {str(e)}")
                                rag_results.append("")
                        
                        # Add RAG results to dataframe
                        df['rag_nist'] = rag_results
                        
                        # Save enhanced dataframe
                        st.session_state['analysis_df_rag'] = df[['interaction_source', 'interaction_target', 'category', 'description', 'rag_nist']]
                        st.session_state['rag_complete'] = True
                        
                        # Clear progress indicators
                        progress_bar.empty()
                        status_text.empty()
                        
                        st.success(f"✅ RAG enhancement completed! Added NIST recommendations for {total_rows} threats.")
                        
                    except Exception as e:
                        st.error(f"❌ Error during RAG enhancement: {str(e)}")
                        st.exception(e)
            
            # Display RAG-enhanced results
            if st.session_state.get('rag_complete', False):
                st.markdown("---")
                st.subheader("📊 Enhanced Results with NIST RAG")
                
                with st.expander("📈 Enhanced DataFrame with RAG", expanded=True):
                    st.dataframe(st.session_state['analysis_df_rag'], width='stretch')
                
                # Download options for enhanced results
                st.markdown("---")
                st.subheader("💾 Download Enhanced Results")
                
                col_rag1, col_rag2 = st.columns(2)
                
                with col_rag1:
                    # Download Enhanced JSON
                    json_str_rag = st.session_state['analysis_df_rag'].to_json()
                    st.download_button(
                        label="📥 Download Enhanced JSON",
                        data=json_str_rag,
                        file_name=f"threat_analysis_rag_{st.session_state['selected_model']}.json",
                        mime="application/json",
                        key="download_rag_json"
                    )
                
                with col_rag2:
                    # Download Enhanced CSV
                    csv_rag = st.session_state['analysis_df_rag'].to_csv(index=False)
                    st.download_button(
                        label="📥 Download Enhanced CSV",
                        data=csv_rag,
                        file_name=f"threat_analysis_rag_{st.session_state['selected_model']}.csv",
                        mime="text/csv",
                        key="download_rag_csv"
                    )
        
    else:
        st.info("⏳ Process the threat model on the left panel to enable AI analysis.")

# Footer
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center; color: gray; padding: 10px;'>
        <small>ITA Threat Modeling Tool - POC | Secure by Design</small>
    </div>
    """,
    unsafe_allow_html=True
)